### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by naisargparmar** [Yqnn/node-readdir-glob#8]
I am using **node version 8.11.2**
readdir-glob nodemodule require node atleast 10
project/node_modules/readdir-glob/index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, shouldSkip, strict) {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by Yqnn** [comment]
Hello,

Indeed, `readdir-glob` uses async generator functions, that were introduced in NodeJS 10.0, it cannot work on older versions.
By the way, NodeJS 8 isn't supported anymore for almost [2 years now](https://en.wikipedia.org/wiki/Node.js#Releases).
